Repository sangyong-99/Team-ARTX-SelfAffirmation, pull requests merged in 2023-11, with the labels that each got.

#11 [Feat] SwiftData, AppStorage
  ARTX-SelfAffirmation.xcodeproj/project.pbxproj
  ARTX-SelfAffirmation/ARTX_SelfAffirmationApp.swift
  ARTX-SelfAffirmation/Assets.xcassets/bg0.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/bg0.imageset/bg1.png
  ARTX-SelfAffirmation/Assets.xcassets/bg1.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/bg1.imageset/bg2.png
  ARTX-SelfAffirmation/Assets.xcassets/bg2.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/bg2.imageset/bg3.png
  ARTX-SelfAffirmation/Assets.xcassets/bg3.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/bg3.imageset/bg4.png
  ARTX-SelfAffirmation/ContentView.swift
  ARTX-SelfAffirmation/Models/SelfCard.swift
  ARTX-SelfAffirmation/Resources/Theme/ThemeCollection.swift
  ARTX-SelfAffirmation/Resources/Theme/ThemeManager.swift
  ARTX-SelfAffirmation/SwiftData/CardContainer.swift
  ARTX-SelfAffirmation/SwiftData/CardData.swift
  ARTX-SelfAffirmation/ViewModels/SelfCardViewModel.swift
  ARTX-SelfAffirmation/Views/SelfCardView.swift
Labels: ✨ Feature

#13 Theme Setting / Notification Manager
  ARTX-SelfAffirmation.xcodeproj/project.pbxproj
  ARTX-SelfAffirmation/ContentView.swift
  ARTX-SelfAffirmation/Extension/NavigationBarModifier.swift
  ARTX-SelfAffirmation/Resources/Theme/Theme.swift
  ARTX-SelfAffirmation/Resources/Theme/ThemeCollection.swift
  ARTX-SelfAffirmation/Views/SelfCardView.swift
  ARTX-SelfAffirmation/Views/SettingAlarmView.swift
  ARTX-SelfAffirmation/Views/SettingInfoView.swift
  ARTX-SelfAffirmation/Views/SettingView.swift
  ARTX-SelfAffirmation/Views/VersionView.swift
  ARTX-SelfAffirmation/Views/WidgetSettingDiscriptionRowView.swift
Labels: ✨ Feature

#16 [Fix] Random Notification
  ARTX-SelfAffirmation/Utils/NotificationManager.swift
  ARTX-SelfAffirmation/Views/SettingAlarmView.swift
  ARTX-SelfAffirmation/Views/SettingView.swift
Labels: :tada: Hotfix

#18 [Chore] Fix Share ratio
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img1.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img1.imageset/img1.jpg
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img10.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img10.imageset/img10.jpg
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img11.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img11.imageset/img11.jpg
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img12.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img12.imageset/img12.jpg
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img13.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img13.imageset/img13.jpg
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img14.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img14.imageset/img14.jpg
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img15.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img15.imageset/img15.jpg
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img16.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img16.imageset/img16.jpg
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img17.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img17.imageset/img17.jpg
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img18.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img18.imageset/img18.jpg
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img19.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img19.imageset/img19.jpg
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img2.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img2.imageset/img2.jpg
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img20.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img20.imageset/img20.jpg
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img3.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img3.imageset/img3.jpg
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img4.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img4.imageset/img4.jpg
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img5.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img5.imageset/img5.jpg
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img6.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img6.imageset/img6.jpg
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img7.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img7.imageset/img7.jpg
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img8.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img8.imageset/img8.jpg
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img9.imageset/Contents.json
  ARTX-SelfAffirmation/Assets.xcassets/BGImages/img9.imageset/img9.jpg
  ARTX-SelfAffirmation/Assets.xcassets/bg0.imageset/bg1.png
  ARTX-SelfAffirmation/Assets.xcassets/bg1.imageset/bg2.png
  ARTX-SelfAffirmation/Assets.xcassets/bg2.imageset/bg3.png
  ARTX-SelfAffirmation/Assets.xcassets/bg3.imageset/bg4.png
  ARTX-SelfAffirmation/SwiftData/CardData.swift
  ARTX-SelfAffirmation/Views/SelfCardView.swift
Labels: ✨ Feature

#20 Fix SettingView
  ARTX-SelfAffirmation.xcodeproj/project.pbxproj
  ARTX-SelfAffirmation/Views/SettingInfoView.swift
  ARTX-SelfAffirmation/Views/SettingView.swift
Labels: :tada: Hotfix

#22 [Fix] Notification
  ARTX-SelfAffirmation/Utils/NotificationManager.swift
  ARTX-SelfAffirmation/Views/SettingAlarmView.swift
Labels: :tada: Hotfix

#24 First sprint fix
  ARTX-SelfAffirmation.xcodeproj/project.pbxproj
  ARTX-SelfAffirmation/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  ARTX-SelfAffirmation/Assets.xcassets/AppIcon.appiconset/Contents.json
  ARTX-SelfAffirmation/Localizable.xcstrings
  ARTX-SelfAffirmation/Views/SelfCardView.swift
  ARTX-SelfAffirmation/Views/VersionView.swift
Labels: :hammer: Release

#28 Detail Fix from Sprint 1.0
  ARTX-SelfAffirmation/ContentView.swift
  ARTX-SelfAffirmation/Localizable.xcstrings
  ARTX-SelfAffirmation/Resources/Theme/ThemeManager.swift
  ARTX-SelfAffirmation/Views/SelfCardView.swift
  ARTX-SelfAffirmation/Views/ShareView.swift
Labels: :tada: Hotfix

#30 Instagram share
  ARTX-SelfAffirmation.xcodeproj/project.pbxproj
  ARTX-SelfAffirmation/ContentView.swift
  ARTX-SelfAffirmation/Info.plist
  ARTX-SelfAffirmation/SwiftData/CardData.swift
  ARTX-SelfAffirmation/Utils/InstagramActivity.swift
  ARTX-SelfAffirmation/Utils/ShareView.swift
  ARTX-SelfAffirmation/Views/InstagramShareView.swift
  ARTX-SelfAffirmation/Views/SelfCardView.swift
Labels: :tada: Hotfix

#31 Fix Setting View Add TabBarView
  ARTX-SelfAffirmation.xcodeproj/project.pbxproj
  ARTX-SelfAffirmation/ARTX_SelfAffirmationApp.swift
  ARTX-SelfAffirmation/ContentView.swift
  ARTX-SelfAffirmation/Localizable.xcstrings
  ARTX-SelfAffirmation/Resources/Theme/Theme.swift
  ARTX-SelfAffirmation/Resources/Theme/ThemeCollection.swift
  ARTX-SelfAffirmation/Views/SelfCardView.swift
  ARTX-SelfAffirmation/Views/SettingInfoView.swift
  ARTX-SelfAffirmation/Views/SettingView.swift
  ARTX-SelfAffirmation/Views/TabBarView.swift
  ARTX-SelfAffirmation/Views/WidgetSettingView.swift
Labels: ✨ Feature
